apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: frontend
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: frontend
