apiVersion: v1
kind: Service
metadata:
  name: rest
  labels:
    app: rest
spec:
  selector:
    app: rest
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30007
