apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: restloadbalancer 
  name: restloadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: restloadbalancer